# -*- coding: utf-8 -*-
"""video summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yH5Z43gN3S8e9j2n9XiKYg4_5x1gU4vZ
"""

import os
import whisper
from static_ffmpeg import add_paths
add_paths()
from moviepy import VideoFileClip
from transformers import pipeline
import yt_dlp
import torch



# -----------------------------
# STEP 1: Download YouTube Video
# -----------------------------
def download_youtube_video(url, output_path="video.mp4"):
    ydl_opts = {
        'format': 'mp4',
        'outtmpl': output_path,
        'quiet': True
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([url])
    return output_path

# -----------------------------
# STEP 2: Extract Audio
# -----------------------------
def extract_audio(video_path, audio_path="audio.wav"):
    video = VideoFileClip(video_path)
    video.audio.write_audiofile(audio_path, logger=None)
    return audio_path

# -----------------------------
# STEP 3: Transcribe Audio
# -----------------------------
def transcribe_audio(audio_path):
    model = whisper.load_model("small")  # best for Colab
    result = model.transcribe(audio_path)
    return result["text"]

# -----------------------------
# STEP 4: Summarize Text
# -----------------------------
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

def summarize_text(text):
    model_name = "facebook/bart-large-cnn"
    device = "cuda" if torch.cuda.is_available() else "cpu"
    
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name).to(device)

    # Split text into chunks that the model can handle
    max_chunk = 1000
    chunks = [text[i:i+max_chunk] for i in range(0, len(text), max_chunk)]

    final_summary = ""
    for chunk in chunks:
        inputs = tokenizer(chunk, return_tensors="pt", max_length=1024, truncation=True).to(device)
        summary_ids = model.generate(inputs["input_ids"], max_length=150, min_length=40, length_penalty=2.0, num_beams=4, early_stopping=True)
        summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
        final_summary += summary + " "

    return final_summary.strip()

# -----------------------------
# STEP 5: Save Summary
# -----------------------------
def save_summary(summary, filename="summary.txt"):
    with open(filename, "w", encoding="utf-8") as f:
        f.write(summary)

# -----------------------------
# MAIN EXECUTION
# -----------------------------
if __name__ == "__main__":

    YOUTUBE_URL = "https://www.youtube.com/watch?v=u5EoIVKd2_M&list=PPSV"

    print("⬇️ Downloading YouTube video...")
    video_path = download_youtube_video(YOUTUBE_URL)

    print("🔊 Extracting audio...")
    audio_path = extract_audio(video_path)

    print("📝 Transcribing audio...")
    transcript = transcribe_audio(audio_path)

    print("📌 Summarizing video...")
    summary = summarize_text(transcript)

    save_summary(summary)

    print("\n✅ FINAL VIDEO SUMMARY:\n")
    print(summary)
    print("\n📁 Saved as summary.txt")